version: 2.1
jobs:
  build:
    working_directory: ~/Vuesplash
    docker:
      - image: circleci/php:7.2.1-apache-node-browsers
      - image: circleci/mysql:5.7

    environment:
      - APP_DEBUG: true
      - APP_ENV: testing
      - APP_KEY: base64:ks5yHQPbF9H2NkAcyNsmv/mEtHHgSlwfPR2Ld1DJPoU=
      - DB_CONNECTION: circle_test
      - MYSQL_ALLOW_EMPTY_PASSWORD: true

    steps:
      # Install PHP Extension
      - run: sudo docker-php-ext-install pdo_mysql

      # Download and cache dependencies
      - restore_cache:
          keys:
              - v1-dependencies-{{ checksum "composer.json" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
              - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # fixer
      - run: composer fixer